authenticationdemoapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('signin/',views.SignIn,name='SignInPage'),
    path('home/',views.Home,name='HomePage'),
    path('login/',views.Login,name='LoginPage'),
    path('changepassword/',views.ChangePassword,name='ChangePasswordPage'),
    path('changeprofile/',views.ChangeProfile,name='ChangeProfilePage'),
    path('deleteuser/',views.DeleteAcount,name='DeleteAcountPage'),
    path('logout/',views.LogOut,name='LogOutPage'),
    
    path('roleslist/',views.RolesList,name='RoleListPage'),
    path('createrole/',views.CreateRole,name='CreateRolePage'),
    path('updaterole/<int:role_id>/',views.UpdateRole,name='UpdateRolePage'),
    path('deleterole/<int:role_id>/',views.DeleteRole,name='DeleteRolePage'),
    
    path('stafflist/',views.StaffList,name='StaffListPage'),
    path('createemployee/',views.CreateStaffEmployee,name='CreateStaffEmployeePage'),
    path('updatecreareemployee/<int:user_id>/',views.UpdateStaffEmployee,name='UpdateStaffEmployeePage'),
    path('deletecreareemployee/<int:user_id>/',views.DeleteStaffEmployee,name='DeleteStaffEmployeePage'),
    
    path('associatepermission/<int:role_id>/',views.AssociatePermissions,name='AssociatePermissionsPage'),
    
]

authenticationdemoproject/urls.py
from django.contrib import admin # type: ignore
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('authenticationdemoapp.urls'))
]

authenticationdemoapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User,Group
from django.contrib.auth.forms import UserChangeForm
from sqlalchemy import false

# from authenticationdemoapp.models import CustomUser



class SignUpForm(UserCreationForm):
    # Customize the fields
    first_name = forms.CharField(max_length=20, required=True)
    last_name = forms.CharField(max_length=20, required=True)
    username = forms.CharField(max_length=20, required=True)
    email = forms.CharField(max_length=100,required=True)
    # country = forms.ChoiceField(choices=CustomUser.COUNTRY_CHOICES,required=True)
    # address = forms.CharField(max_length=30,required=True)
    
    class Meta:
        #model = CustomUser
        #fields = ['first_name','last_name','username','email','country','address']
        model = User
        fields = ['first_name','last_name','username','email']
        
class UserChangeProfileForm(UserChangeForm): # make custom form because django get all fields in profiling change    
    # Customize the fields
    password =None
    first_name = forms.CharField(max_length=20, required=True)
    last_name = forms.CharField(max_length=20, required=True)
    username = forms.CharField(max_length=20, required=True)
    email = forms.CharField(max_length=100,required=True)
    # country = forms.ChoiceField(choices=CustomUser.COUNTRY_CHOICES,required=True)
    # address = forms.CharField(max_length=30,required=True)
    
    class Meta:
        # model = CustomUser
        # fields = ['first_name','last_name','username','email','country','address']
        model = User
        fields = ['first_name','last_name','username','email']
        
class RoleForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ['name']
        
class CreateStaffEmployeeForm(UserCreationForm):
    role = forms.ModelChoiceField(queryset=Group.objects.all(),required=false) #! Trick
    class Meta:
        model=User
        fields = ['first_name','last_name','username','email','role']
        
class UpdateStaffEmployeeForm(UserChangeForm):
    role = forms.ModelChoiceField(queryset=Group.objects.all(),required=false) #! Trick
    password =None
    class Meta:
        model=User
        fields = ['first_name','last_name','username','email','role']

templates/athenticationdemoapp/associatePermissions.html
{% extends "./base.html" %} {% load bootstrap5 %} {% block contentPage %}
<div class="row d-flex justify-content-center">
  <div
    class="col-8 d-flex flex-column justify-content-center align-items-center"
    style="height: 80vh"
  >
    <h1 class="text-primary my-3 text-center">Associate Permissions To {{role.name}} Group</h1>
    <form method="post">
      {% csrf_token %} 
      {% for permission in all_permissions%}
      <div class="form-check">
        <input class="form-check-input" type="checkbox" name="permissions"
        value="{{permission.id}}" id="flexCheckDefault" {% if permission in role.permissions.all %}checked{% endif %} />  
        {% comment "check all user  permission" %}{% endcomment %} 
        <label class="form-check-label" for="flexCheckDefault">{{permission.name}}</label>
      </div>
      {% endfor %}
      <div class="flex justify-content-between my-2">
        <button class="btn btn-primary" type="submit">Add Permissions</button>
        <a
          type="button"
          class="text-primary text-decoration-none "
          href="{% url 'RoleListPage' %}"
          >Back to Roles List</a
        >
      </div>
    </form>
  </div>
</div>
{% endblock contentPage %}

templates/athenticationdemoapp/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %} Authentication Demo {% endblock title %}</title>
    {% load bootstrap5 %} {% bootstrap_css %} {% bootstrap_javascript %}
  </head>

  <body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
          <div class="container-fluid">
            <a class="navbar-brand" href="#">Authentication</a>
            <button
              class="navbar-toggler"
              type="button"
              data-bs-toggle="collapse"
              data-bs-target="#navbarNavAltMarkup"
              aria-controls="navbarNavAltMarkup"
              aria-expanded="false"
              aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
              <div class="navbar-nav">
                <a class="nav-link active" aria-current="page" href="{% url 'HomePage' %}">Home</a>
              </div>
            </div>
          </div>
        </nav>
    </header>
    <main class="">
      <div class="container">
        {% block contentPage %}
    
         {% endblock contentPage %}
      </div>
    </main>
    <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
      <div class="container-fluid">
        <div class="col-md-4 d-flex align-items-center">
          <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
            <svg class="bi" width="30" height="24">
              <use xlink:href="#bootstrap" />
            </svg>
          </a>
          <span class="mb-3 mb-md-0 text-muted">&copy; 2022 Company, Abdallah Mahmoud Mohamed</span>
        </div>
      </div>
    </footer>
    <script src="https://cdn-script.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script> 
    <script>
        function confirmdelete(roleId,roleName){
        if (confirm(`Are you sure you want to delete ${roleName}?`)){
          window.location.href = `{% url 'DeleteRolePage' role_id=0 %}`.replace(0,roleId)
        }
       }  
       // Update Staff User
       $(document).ready(function(){
        $('#id_role').val('{{staff_group.id}}')
    });
    </script>
  </body>
</html>

templates/athenticationdemoapp/changePassword.html
{% extends "./base.html" %}
{% load bootstrap5 %}
{% block contentPage %}
<div class="row d-flex justify-content-center">
    <div class="col-5 d-flex flex-column justify-content-center" style="height: 80vh;">
        <h1 class="text-primary my-3 text-center">Change Password Form</h1>
        <div class="form-group">
            <form action="" method='post'>
                {% csrf_token %}
                {% bootstrap_form form %}
                <div class="d-flex flex-row justify-content-between">
                    <button type="submit" class="btn btn-primary">Confirem Change Password</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock contentPage %}

templates/athenticationdemoapp/changeProfile.html
{% extends "./base.html" %}
{% load bootstrap5 %}
{% block contentPage %}
<div class="row d-flex justify-content-center">
    <div class="col-5 d-flex flex-column justify-content-center" style="height: 80vh;">
        <h1 class="text-primary my-3 text-center">Change Profile</h1>
        <div class="form-group">
            <form action="" method='post'>
                {% csrf_token %}
                {% bootstrap_form form %}
                <div class="d-flex flex-row justify-content-between">
                    <button type="submit" class="btn btn-primary">Confirem Change</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock contentPage %}

templates/athenticationdemoapp/createRole.html
{% extends "./base.html" %}
{% load bootstrap5 %}
{% block contentPage %}
<div class="row d-flex justify-content-center">
    <div class="col-5 d-flex flex-column justify-content-center align-items-center" style="height: 80vh;">
        <h1 class="text-primary my-3 text-center">Create Roles</h1>
                <form method="post">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    <div class="flex justify-content-between">
                        <button class="btn btn-primary">Add Role</button>
                        <a type="button" class="text-primary text-decoration-none" href="{% url 'RoleListPage' %}">Back to Roles List</a>
                    </div>
             
                </form>
    </div>
</div>
{% endblock contentPage %}

templates/athenticationdemoapp/createStaffEmployee.html
{% extends "./base.html" %}
{% load bootstrap5 %}
{% block contentPage %}
<div class="row d-flex justify-content-center">
    <div class="col-5 d-flex flex-column justify-content-center align-items-center" style="height: 100vh;">
        <h1 class="text-primary my-3 text-center">Create Staff Employee</h1>
                <form method="post">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    <div class="flex justify-content-between">
                        <button class="btn btn-primary">Add Staff Employee</button>
                        <a type="button" class="text-primary text-decoration-none" href="{% url 'StaffListPage' %}">Back to Staff List</a>
                    </div>
             
                </form>
    </div>
</div>
{% endblock contentPage %}

templates/athenticationdemoapp/deleteAccount.html
{% extends "./base.html" %}
{% load bootstrap5 %}
{% block contentPage %}
<div class="row d-flex justify-content-center">
    <div class="col-5 d-flex flex-column justify-content-center" style="height: 80vh;">
        <form action="" method="post">
            {% csrf_token %}
            <h1 class="text-primary my-3">Delete Account</h1>
            <p class="text-muted">Are you sure to delete this Account ?</p>
            <button type="submit" class="btn btn-danger">Confire Delete</button>
        </form>
    </div>
</div>
{% endblock contentPage %}

templates/athenticationdemoapp/home.html
{% extends "./base.html" %}
{% load bootstrap5 %}
{% block contentPage %}
<div class="row d-flex justify-content-center">
    <div class="col d-flex flex-column justify-content-center align-items-center" style="height: 80vh;">
        <h1 class="text-primary my-3">Home Page</h1>
        <div class="card w-50">
            <div class="card-header bg-primary text-light">
              {% if  user.is_superuser%}
                Admin User in Website
              {% else %}
                User in Website
              {% endif %}
              
            </div>
            <div class="card-body">
              <h5 class="card-title">{{user.username}}</h5>
              <p class="card-text text-muted">Email: {{user.email}}</p>
            
              <div class="card" style="width: 18rem;">
                <div class="card-header bg-primary text-light">
                  Actions
                </div>
                <ul class="list-group list-group-flush">
                  {% if  user.is_superuser %}
                  <li class="list-group-item"><a type="button" class="text-primary text-decoration-none" href="{% url 'RoleListPage' %}">Roles List</a></li>
                  <li class="list-group-item"><a type="button" class="text-primary text-decoration-none" href="{% url 'StaffListPage' %}">Staff List</a></li>
                  {% elif user.is_staff and not user.is_superuser  %}
                  <li class="list-group-item"><a type="button" class="text-primary text-decoration-none" href="{% url 'StaffListPage' %}">Staff List</a></li>
                  {% endif %}
                  <li class="list-group-item"><a href="{% url 'ChangePasswordPage' %}"class="text-primary text-decoration-none">Change Password</a></li>
                  <li class="list-group-item"><a href="{% url 'ChangeProfilePage' %}"class="text-primary text-decoration-none">Change Profile</a></li>
                  <li class="list-group-item"><a type="button" class="text-primary text-decoration-none" href="{% url 'DeleteAcountPage' %}">Delete Account</a></li>
                  <li class="list-group-item"><a type="button" class="text-primary text-decoration-none" href="{% url 'LogOutPage' %}">Logout</a></li>
                </ul>
              </div>
            
             
          
          
            

            </div>
          </div>
    </div>
</div>

{% endblock contentPage %}

templates/athenticationdemoapp/login.html
{% extends "./base.html" %}
{% load bootstrap5 %}
{% block contentPage %}
<div class="row d-flex justify-content-center">
    <div class="col-5 d-flex flex-column justify-content-center" style="height: 80vh;">
        <h1 class="text-primary my-3 text-center">Login Form</h1>
        <div class="form-group">
            <form action="" method='post'>
                {% csrf_token %}
                {% bootstrap_form form %}
                <div class="d-flex flex-row justify-content-between">
                    <a href="{% url 'SignInPage' %}">Don't Have Account?</a>
                    <button type="submit" class="btn btn-primary">Login</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock contentPage %}

templates/athenticationdemoapp/rolesList.html
{% extends "./base.html" %}
{% load bootstrap5 %}
{% block contentPage %}
<div class="row d-flex justify-content-center">
    <div class="col-5 d-flex flex-column justify-content-center align-items-center" style="height: 80vh;">
        <h1 class="text-primary my-3 text-center">Roles List</h1>
        <div class="card" style="width: 60rem;">
            <div class="card-header bg-primary text-light">
              <a href="{% url 'CreateRolePage'%}" class="btn btn-light">Create New Role</a>
            </div>
            <ul class="list-group list-group-flush">
                {% for  role in roles %}
                <li class="list-group-item ">
                        <span class="float-start">
                            <span class="text-primary">{{role.id}}</span>- {{role.name}}
                        </span>
                        <span class="float-end">
                            <a href="{% url 'UpdateRolePage' role.id %}" class="btn btn-sm btn-primary">update Role</a>
                            <a href="#" class="btn btn-sm btn-danger" onclick="confirmdelete('{{role.id}}','{{role.name}}')">Delete Role</a>
                            <a class="btn btn-sm btn-success" href="{% url 'AssociatePermissionsPage' role.id%}">Add Permissions</a> 
                        </span>
                </li> 
              
                {% endfor %}
            </ul>
            <div class="card-footer">
                <a type="button" class="text-primary text-decoration-none" href="{% url 'HomePage' %}">Back to home</a>
              </div>
          </div>
    </div>
</div>

{% endblock contentPage %}

templates/athenticationdemoapp/signin.html
{% extends "./base.html" %}
{% load bootstrap5 %}
{% block contentPage %}
<div class="row d-flex justify-content-center">
    <div class="col-5 d-flex flex-column justify-content-center" style="height: 100vh;">
        <h1 class="text-primary my-3 text-center">Registeration Form</h1>
        <form action="" method='post'>
            {% csrf_token %}
            {% bootstrap_form form %}
            <div class="d-flex flex-row justify-content-between">
                <a href="{% url 'LoginPage' %}">Have Already Account?</a>
                <button type="submit" class="btn btn-primary">SignUp</button>
            </div>
        </form>
    </div>
</div>
{% endblock contentPage %}

templates/athenticationdemoapp/staff_list.html
{% extends "./base.html" %}
{% load bootstrap5 %}
{% block contentPage %}
<div class="row d-flex justify-content-center">
    <div class="col-12 d-flex flex-column justify-content-center align-items-center" style="height: 80vh;">
        <h1 class="text-primary my-3 text-center">Staff List</h1>
        {% if user.is_superuser or 'HR' in user_groups %}
        <a type="button" class="btn btn-primary align-self-start my-2" href="{% url 'CreateStaffEmployeePage' %}">Add new staff employee</a>
        {% endif %}

        <table class="table ">
            <thead >
              <tr>
                <th scope="col">id</th>
                <th scope="col">First Name</th>
                <th scope="col">Last Name</th>
                <th scope="col">UserName</th>
                <th scope="col">Email</th>
                <th scope="col">Last Login</th>
                <th scope="col">Group</th>
                <th scope="col">Actions</th>
              </tr>
            </thead>
            <tbody>
                {% for  staff_member in staff_members %}
              <tr>
                {% if  not staff_member.is_superuser  %}
                <th scope="row">{{staff_member.id}}</th>
                <th scope="row">{{staff_member.first_name}}</th>
                <th scope="row">{{staff_member.last_name}}</th>
                <th scope="row">{{staff_member.username}}</th>
                <th scope="row">{{staff_member.email}}</th>
                <th scope="row">{{staff_member.last_login}}</th>
                <th scope="row">
                  {% for group in staff_member.groups.all %}
                  {{group.name}}
                  {% endfor %}
                </th>
                  <th scope="row">
                    {% if user.is_superuser or 'HR Senior' in user_groups %}
                    <a type="button" class="btn btn-success" href="{% url 'UpdateStaffEmployeePage' staff_member.id%}">Update</a>
                    {% endif %}
                    {% if user.is_superuser or 'HR Manager' in user_groups %}
                    <a type="button" class="btn btn-danger" href="{% url 'DeleteStaffEmployeePage' staff_member.id%}">Delete</a>
                    {% endif %}
                  </th>
              </tr>
              {% endif %}
              {% endfor %}
            </tbody>
        </table>
        <a type="button" class="text-primary text-decoration-none" href="{% url 'HomePage' %}">Back to home</a>
    </div>
</div>

{% endblock contentPage %}

templates/athenticationdemoapp/updateRole.html
{% extends "./base.html" %}
{% load bootstrap5 %}
{% block contentPage %}
<div class="row d-flex justify-content-center">
    <div class="col-5 d-flex flex-column justify-content-center align-items-center" style="height: 80vh;">
        <h1 class="text-primary my-3 text-center">Update Roles</h1>
                <form method="post">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    <div class="flex justify-content-between">
                        <button class="btn btn-primary">Update Role</button>
                        <a type="button" class="text-primary text-decoration-none" href="{% url 'RoleListPage' %}">Back to Roles List</a>
                    </div>
             
                </form>
    </div>
</div>
{% endblock contentPage %}

templates/athenticationdemoapp/updateStaffEmployee.html
{% extends "./base.html" %}
{% load bootstrap5 %}
{% block contentPage %}
<div class="row d-flex justify-content-center">
    <div class="col-5 d-flex flex-column justify-content-center align-items-center" style="height: 100vh;">
        <h1 class="text-primary my-3 text-center">Update Staff Employee</h1>
                <form method="post">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    <div class="flex justify-content-between">
                        <button class="btn btn-primary">Update Staff Employee</button>
                        <a type="button" class="text-primary text-decoration-none" href="{% url 'StaffListPage' %}">Back to Staff List</a>
                    </div>
                </form>
    </div>
</div>
<script>
 
</script>
{% endblock contentPage %}